# Generated by Django 4.1.1 on 2022-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resenha",
            name="estrela",
            field=models.DecimalField(
                choices=[
                    (1, "1 estrela"),
                    (1.5, "1.5 estrela"),
                    (2, "2 estrelas"),
                    (2.5, "2.5 estrelas"),
                    (3, "3 estrelas"),
                    (3.5, "3.5 estrelas"),
                    (4, "4 estrelas"),
                    (4.5, "4.5 estrelas"),
                    (5, "5 estrelas"),
                ],
                decimal_places=1,
                max_digits=2,
            ),
        ),
    ]
