# Generated by Django 4.1.3 on 2022-11-01 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='askon/jogos/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='data da publicacao'),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
