# Generated by Django 4.1.1 on 2022-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_resenha_estrela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resenha",
            name="estrela",
            field=models.IntegerField(
                choices=[
                    (1.0, "1 estrela"),
                    (2.0, "2 estrelas"),
                    (3.0, "3 estrelas"),
                    (4.0, "4 estrelas"),
                    (5.0, "5 estrelas"),
                ]
            ),
        ),
    ]
