# Generated by Django 4.1.3 on 2022-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resenha_imagem_resenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='askon/perfil'),
        ),
    ]
