# Generated by Django 4.1.3 on 2022-12-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_imagem_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenha',
            name='estrela',
        ),
        migrations.AddField(
            model_name='resenha',
            name='nota_audio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resenha',
            name='nota_cenario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resenha',
            name='nota_grafico',
            field=models.IntegerField(default=0),
        ),
    ]
